language: julia
os:
    - osx
    - linux
    - windows
julia:
    - 1
    - nightly
matrix:
    allow_failures:
        - julia: nightly
notifications:
    email: false
after_success:
    - julia -e 'import Pkg; cd(Pkg.dir("QuantumOptics")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
    - julia -e 'import Pkg; cd(Pkg.dir("QuantumOptics")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
